name: figma_flutter_generator
description: A command-line tool to fetch SVG icons from Figma and convert them into an icon font, along with Figma variables to Flutter theme files.
version: 0.0.6
repository: https://github.com/Shopbox-Aps/figma_flutter_generator.git

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  args: ^2.4.2
  http: ^1.1.0
  path: ^1.8.3
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  mockito: ^5.4.2
  build_runner: ^2.4.6

executables:
  figma_flutter_generator: figma_flutter_generator

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: IconFont
      fonts:
        - asset: fonts/icon_font.ttf

export:
  - lib/figma_flutter_generator.dart
  - lib/figma_variables_fetcher.dart
